spring.application.name=datos-mapas

# Conexión a DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

# Configuración Hibernate para PostGIS
# spring.jpa.database-platform=org.hibernate.spatial.dialect.postgis.PostgisPGDialect
spring.jpa.hibernate.ddl-auto=none

# Mostrar SQL en consola (opcional para desarrollo)
spring.jpa.show-sql=true

# Evitar cache de recursos estaticos (JS/CSS) en navegador
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.must-revalidate=true
